// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDof-JgPasg2h6YlXDYtvh4JdsdHtg9css',
    appId: '1:104455039089:web:16df935efd44e4f28713d0',
    messagingSenderId: '104455039089',
    projectId: 'pocketday-1679a',
    authDomain: 'pocketday-1679a.firebaseapp.com',
    storageBucket: 'pocketday-1679a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvV-GckjW4qRkJ2YyqXcZxsS4whPxnO1M',
    appId: '1:104455039089:android:ff170940169db8258713d0',
    messagingSenderId: '104455039089',
    projectId: 'pocketday-1679a',
    storageBucket: 'pocketday-1679a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF3l7qkYZSMZkz66JqSMMMNUVfkh5zz5Y',
    appId: '1:104455039089:ios:5fc711acf1945e5f8713d0',
    messagingSenderId: '104455039089',
    projectId: 'pocketday-1679a',
    storageBucket: 'pocketday-1679a.firebasestorage.app',
    iosClientId: '104455039089-3oh38eovk9vfdgatnprb2ho2tn61r613.apps.googleusercontent.com',
    iosBundleId: 'com.wclabs.pocketday',
  );
}
